In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("final_cleaned_data.csv", sep = ';' )
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,-5.176,0.033,0.483,0.000,...,Artist 1,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...,0.849862
1,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,-4.019,0.061,0.143,0.629,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...,0.883423
2,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,-5.678,0.333,0.213,0.000,...,Artist 1,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...,0.835301
3,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,-8.332,0.033,0.435,0.000,...,Artist 1,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7,https://open.spotify.com/track/7FbrGaHYVDmfr7K...,0.758318
4,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,-4.076,0.047,0.228,0.000,...,Artist 1,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK,https://open.spotify.com/track/6pD0ufEQq0xdHSs...,0.881769

In [3]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
print(df['Date'].dtypes)

datetime64[ns]

In [4]:
df[df.duplicated(subset=['Title','Date','Artists'], keep=False)]

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,# of Artist,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm
7996,21,Chemical,Post Malone,2023-04-14,0.498,0.897,-4.907,0.045,0.001,0.000,...,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,180,180.0,5w40ZYhbBMAlHYNDaVJIUu,https://open.spotify.com/track/5w40ZYhbBMAlHYN...,0.857665
7997,173,Chemical,Post Malone,2023-04-14,0.480,0.895,-4.872,0.043,0.002,0.000,...,Artist 1,Post Malone,Nationality 1,United States,Anglo-America,28,28.0,4qzEjmuz380jeiBJp31oDY,https://open.spotify.com/track/4qzEjmuz380jeiB...,0.858680
27221,2,Rockin' Around The Christmas Tree,Brenda Lee,2022-12-25,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,199,199.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
27222,156,Rockin' Around The Christmas Tree,Brenda Lee,2022-12-25,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,45,45.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
27397,3,Rockin' Around The Christmas Tree,Brenda Lee,2022-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
27398,108,Rockin' Around The Christmas Tree,Brenda Lee,2022-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,93,93.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
88778,188,Take My Breath,The Weeknd,2022-01-13,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,13,13.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
88779,51,Take My Breath,The Weeknd,2022-01-13,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,150,150.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
88956,180,Take My Breath,The Weeknd,2022-01-12,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,21,21.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
88957,38,Take My Breath,The Weeknd,2022-01-12,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,163,163.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
89135,171,Take My Breath,The Weeknd,2022-01-11,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,30,30.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
89136,28,Take My Breath,The Weeknd,2022-01-11,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,173,173.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
89314,160,Take My Breath,The Weeknd,2022-01-10,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,41,41.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
89315,23,Take My Breath,The Weeknd,2022-01-10,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,178,178.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
89495,186,Take My Breath,The Weeknd,2022-01-09,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,15,15.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
89496,20,Take My Breath,The Weeknd,2022-01-09,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,181,181.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
89672,157,Take My Breath,The Weeknd,2022-01-08,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,44,44.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
89673,16,Take My Breath,The Weeknd,2022-01-08,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,185,185.0,2vgUijXOTRMnWXDtvgMp2b,https://open.spotify.com/track/2vgUijXOTRMnWXD...,0.792487
89847,151,Take My Breath,The Weeknd,2022-01-07,0.747,0.739,-6.008,0.049,0.011,0.000,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,50,50.0,6M3PsepEj5gyJoIi7Xvr7u,https://open.spotify.com/track/6M3PsepEj5gyJoI...,0.825729
89848,13,Take My Breath,The Weeknd,2022-01-07,0.698,0.769,-7.154,0.037,0.013,0.002,...,Artist 1,The Weeknd,Nationality 1,Canada,Anglo-America,188,188.0,0XvDZGVqGYM7P4rgzRnWhq,https://open.spotify.com/track/0XvDZGVqGYM7P4r...,0.792487
92228,3,Rockin' Around The Christmas Tree,Brenda Lee,2021-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
92370,164,Rockin' Around The Christmas Tree,Brenda Lee,2021-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,37,37.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
132671,18,9 5 . s o u t h,J. Cole,2021-05-14,0.713,0.793,-5.277,0.397,0.271,0.000,...,Artist 1,J. Cole,Nationality 1,United States,Anglo-America,183,183.0,5R691ipUYRDYW6ehapjoj6,https://open.spotify.com/track/5R691ipUYRDYW6e...,0.846933
157873,3,Rockin' Around The Christmas Tree,Brenda Lee,2020-12-25,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,198,198.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
157874,185,Rockin' Around The Christmas Tree,Brenda Lee,2020-12-25,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,16,16.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
158056,6,Rockin' Around The Christmas Tree,Brenda Lee,2020-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,195,195.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
158057,132,Rockin' Around The Christmas Tree,Brenda Lee,2020-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,69,69.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
224064,7,Rockin' Around The Christmas Tree,Brenda Lee,2019-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,194,194.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
224065,153,Rockin' Around The Christmas Tree,Brenda Lee,2019-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,48,48.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
290352,7,Rockin' Around The Christmas Tree,Brenda Lee,2018-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,194,194.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
290353,151,Rockin' Around The Christmas Tree,Brenda Lee,2018-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,50,50.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
324443,109,the light is coming (feat. Nicki Minaj),Ariana Grande,2018-06-20,0.879,0.544,-5.667,0.151,0.015,0.000,...,Artist 1,Ariana Grande,Nationality 1,United States,Anglo-America,92,92.0,5iZ4hcpCgFVijq5OOjBTKZ,https://open.spotify.com/track/5iZ4hcpCgFVijq5...,0.835620
346415,20,Amorfoda,Bad Bunny,2018-02-20,0.742,0.432,-7.539,0.062,0.984,0.000,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,181,181.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...,0.781320
346416,162,Amorfoda,Bad Bunny,2018-02-20,0.616,0.587,-6.439,0.091,0.978,0.006,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,39,39.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...,0.813227
346598,29,Amorfoda,Bad Bunny,2018-02-19,0.742,0.432,-7.539,0.062,0.984,0.000,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,172,172.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...,0.781320
346599,106,Amorfoda,Bad Bunny,2018-02-19,0.616,0.587,-6.439,0.091,0.978,0.006,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,95,95.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...,0.813227
346783,37,Amorfoda,Bad Bunny,2018-02-18,0.742,0.432,-7.539,0.062,0.984,0.000,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,164,164.0,3ITvHA9zhZZdBJsOsAUegF,https://open.spotify.com/track/3ITvHA9zhZZdBJs...,0.781320
346784,106,Amorfoda,Bad Bunny,2018-02-18,0.616,0.587,-6.439,0.091,0.978,0.006,...,Artist 1,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,95,95.0,3zaMCRR8g6AvyMLMcuQ73N,https://open.spotify.com/track/3zaMCRR8g6AvyML...,0.813227
357295,11,Rockin' Around The Christmas Tree,Brenda Lee,2017-12-24,0.589,0.472,-8.749,0.050,0.614,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,190,190.0,2EjXfH91m7f8HiJN1yQg97,https://open.spotify.com/track/2EjXfH91m7f8HiJ...,0.746222
357297,158,Rockin' Around The Christmas Tree,Brenda Lee,2017-12-24,0.682,0.641,-8.915,0.039,0.568,0.000,...,Artist 1,Brenda Lee,Nationality 1,United States,Anglo-America,43,43.0,09OojFvtrM9YRzRjnXqJjA,https://open.spotify.com/track/09OojFvtrM9YRzR...,0.741407
437786,19,9 5 . s o u t h,J. Cole,2021-05-14,0.622,0.794,-4.450,0.438,0.228,0.000,...,Artist 1,J. Cole,Nationality 1,United States,Anglo-America,182,182.0,4GSBObGq3DuiKFlytKBbEw,https://open.spotify.com/track/4GSBObGq3DuiKFl...,0.870921
446248,2,Toosie Slide,Drake,2020-04-03,0.834,0.454,-9.750,0.201,0.321,0.000,...,Artist 1,Drake,Nationality 1,Canada,Anglo-America,199,199.0,127QTOFJsJQp5LbJbu3A1y,https://open.spotify.com/track/127QTOFJsJQp5Lb...,0.717186
446249,138,Toosie Slide,Drake,2020-04-03,0.832,0.431,-9.810,0.197,0.344,0.000,...,Artist 1,Drake,Nationality 1,Canada,Anglo-America,63,63.0,1d2eMMrAuIsw85u3YklKoc,https://open.spotify.com/track/1d2eMMrAuIsw85u...,0.715446
457980,197,the light is coming (feat. Nicki Minaj),Ariana Grande,2018-06-20,0.879,0.547,-5.670,0.148,0.015,0.000,...,Artist 1,Ariana Grande,Nationality 1,United States,Anglo-America,4,4.0,397Un0hOSVgAdLcIHpGAxp,https://open.spotify.com/track/397Un0hOSVgAdLc...,0.835533

In [5]:
df['id'].unique()

array(['3qQbCzHBycnDpGskqOWY0E', '7ro0hRteUMfnOioTFI5TG1',
       '2UW7JaomAMuX9pZrjVpHAU', ..., '2Ae5awwKvQpTBKQHr1TYCg',
       '0Tel1fmuCxEFV6wBLXsEdk', '1pWYnQIlqxTh5bxuPmTG4E'],
      shape=(9161,), dtype=object)

In [6]:
df_top_50 = df[df['Rank'] <= 50].copy()
df_top_50['first_top_50_date'] = (
    df_top_50.groupby(['id'])['Date']
    .transform('min')
)
song_stay_in_top_50 = df_top_50[df_top_50['Date'] - df_top_50['first_top_50_date'] > pd.Timedelta(14)]


song_stay_in_top_50['id'].nunique()
song_stay_in_top_50['id'].nunique() / df['id'].nunique()

0.26176181639559

In [41]:
print(f"number of popular songs: { song_stay_in_top_50['id'].unique().shape[0]} ")
print(f"number of total songs: {df['id'].nunique()}")
print(f"Percentage of popular songs: {(song_stay_in_top_50['id'].nunique() / df['id'].nunique())*100:.2f}%")

number of popular songs: 2398
number of total songs: 9161
Percentage of popular songs: 26.18%

### Label column popular in dataset

In [9]:
popular_ids = song_stay_in_top_50['id'].unique()
df['Popular'] = df['id'].isin(popular_ids).astype(int)

In [10]:
df.head()

,Rank,Title,Artists,Date,Danceability,Energy,Loudness,Speechiness,Acousticness,Instrumentalness,...,Artist (Ind.),# of Nationality,Nationality,Continent,Points (Total),Points (Ind for each Artist/Nat),id,Song URL,Loudness_norm,Popular
0,1,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2023-05-29,0.668,0.758,-5.176,0.033,0.483,0.000,...,Eslabon Armado,Nationality 1,Mexico,Latin-America,200,100.0,3qQbCzHBycnDpGskqOWY0E,https://open.spotify.com/track/3qQbCzHBycnDpGs...,0.849862,1
1,2,WHERE SHE GOES,Bad Bunny,2023-05-29,0.652,0.800,-4.019,0.061,0.143,0.629,...,Bad Bunny,Nationality 1,Puerto Rico,Latin-America,199,199.0,7ro0hRteUMfnOioTFI5TG1,https://open.spotify.com/track/7ro0hRteUMfnOio...,0.883423,1
2,3,La Bebe - Remix,"Yng Lvcas, Peso Pluma",2023-05-29,0.812,0.479,-5.678,0.333,0.213,0.000,...,Yng Lvcas,Nationality 1,Mexico,Latin-America,198,99.0,2UW7JaomAMuX9pZrjVpHAU,https://open.spotify.com/track/2UW7JaomAMuX9pZ...,0.835301,1
3,4,Cupid - Twin Ver.,FIFTY FIFTY,2023-05-29,0.783,0.592,-8.332,0.033,0.435,0.000,...,FIFTY FIFTY,Nationality 1,South Korea,Asia,197,197.0,7FbrGaHYVDmfr7KoLIZnQ7,https://open.spotify.com/track/7FbrGaHYVDmfr7K...,0.758318,1
4,5,un x100to,"Grupo Frontera, Bad Bunny",2023-05-29,0.569,0.724,-4.076,0.047,0.228,0.000,...,Grupo Frontera,Nationality 1,Mexico,Latin-America,196,98.0,6pD0ufEQq0xdHSsRbg9LBK,https://open.spotify.com/track/6pD0ufEQq0xdHSs...,0.881769,1

In [13]:
print(df[df['Popular'] == 1]['Popular'].count())

322672

### Check each song has same popularity

In [31]:
check_pop = df.groupby('id')['Popular'].nunique()
print(check_pop)
inconsistent_songs = check_pop[check_pop > 1]

print(len(inconsistent_songs))

id
000xQL6tZNLJzIrtIgxqSl    1
003VDDA7J3Xb2ZFlNx7nIZ    1
003eoIwxETJujVWmNFMoZy    1
003vvx7Niy0yvhvHt4a68B    1
00B7TZ0Xawar6NZ00JFomN    1
                         ..
7zjEyeBsaw9gV0jofJLfOM    1
7zl7kehxesNEo2pYkKXTSe    1
7znO2T2deQ7nZUbyxEAMDB    1
7zvfDihYiJ8RQ1nRcpKBF5    1
7zxRMhXxJMQCeDDg0rKAVo    1
Name: Popular, Length: 9161, dtype: int64
0

In [43]:
df_song = df.drop_duplicates(subset=['id'], keep='first')

In [45]:
df_song.shape

(9161, 22)

In [48]:
print("number of popular song",df_song[df_song['Popular']==1]['Popular'].count())
print("number of unpopular song",df_song[df_song['Popular']==0]['Popular'].count())

number of popular song 2398
number of unpopular song 6763

In [50]:
df_song.to_csv('label_data.csv', sep = ';', index = False)